# Generated by Django 4.1 on 2022-09-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFami', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rutpersona',
            field=models.IntegerField(unique='true'),
        ),
    ]
